### ISSUE TITLE
Selections don't work in Firefox Browser

### ISSUE THREAD

**Issue by BennoB666** [Willy-Kimura/HotkeyListener#10]
When i try the Demo-project and highlighted text in Firefox and press the hotkey, the hotkeylistener get the URL not the highlighted text.

**Comment by BennoB666** [comment]
In Chrome also. It is possible to select the URL but text is not copied to the form.

OS: Windows 10 64bit

**Comment by Willy-Kimura** [comment]
Yes. As reported before, browser text selections esp. from the address bar, fails in some instances due to browser behaviour when handling texts.

Will be working on customizing text capture in browsers.

**Comment by Willy-Kimura** [comment]
You may now test this issue with the [latest release](https://www.nuget.org/packages/HotkeyListener/1.8.0), `v1.8.0`.
