### ISSUE TITLE
Question: Sending an hotkey stored class Hotkey to windows application

### ISSUE THREAD

**Issue by MerlinCooper** [Willy-Kimura/HotkeyListener#13]
Found today the HotkeyListener on NuGet. 

Would like to use it in an application were the user can define a hotkey which will be used to remotely control another application. But I seem to miss how I can send the short-cut. 

P.S.:  The application I'm working on is using the Win32 function keybd_event - which is already superseded by another function. Thus I will have to update the code anyway. But if possible I would right away start using a more convenient solution.  

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-keybd_event

**Comment by Willy-Kimura** [comment]
Quite interesting. What about serializing a Hotkey instance in string format before sending it then deserializing it back to an object once received? You can use a socket stream to connect both the client and server computers then send the serialized copy of the hotkey to the other machine. Upon receiving the serialized hotkey, you will need to have a server app version with HotkeyListener installed to deserialize the received hotkey string and register it before invoking the required command.

Checkout some simple .Net socket helpers:

1. https://github.com/godsharp/GodSharp.Socket
2. https://github.com/aquamoth/SocketMessaging
