### ISSUE TITLE
Creation of HotKey Class instance using a string only works if correct upper/lowercase is used

### ISSUE THREAD

**Issue by MerlinCooper** [Willy-Kimura/HotkeyListener#14]
Using a string to create an instance of class Hotkey works only if the notation (upper/lower-case) exactly matches the one in the source code due to case sensitive parsing. 

As an example using a string all lower-case or all upper case would fail: 
`Hotkey hotkey2 = new Hotkey("control+shift+d4");`
`Hotkey hotkey2 = new Hotkey("CONTROL+SHIFT+D4");`

**Comment by Willy-Kimura** [comment]
Great, thanks!
