### ISSUE TITLE
save hotkey in settings

### ISSUE THREAD

**Issue by BennoB666** [Willy-Kimura/HotkeyListener#16]
Hello,
i use your library in a project and it works very well. Is it possible to store the hotkey in Settings.settings or something else? Can i find an example for this?

thanks a lot and best regards
Benno

**Comment by Willy-Kimura** [comment]
Hello Benno,

Great to hear! Yes, that's very possible actually. You can save the hotkey in string format, e.g. `myHotkey.ToString()`, then upon retrieving it you can convert it into a `Hotkey` object, e.g. `Hotkey myHotkey = HotkeyListener.Convert(myHotkeyInStringForm)` and register it once the application starts.

Try this and let me know.

**Comment by BennoB666** [comment]
Thx a lot.

**Comment by nirit100** [comment]
Hi, 
Sorry if this comes here post-mortem, but I have an issue with this approach. I am currently doing exactly as suggested by you, @Willy-Kimura -- I have a string representation of the shortcut ("`LWin, Alt + S`"), but when I try to make a `HotKey` object out of it (via construction or via `Hotkey myHotkey = HotkeyListener.Convert(myHotkeyInStringForm)`, I get a `System.ArgumentException` with message "`Der angeforderte Wert "LWinS" konnte nicht gefunden werden.`" (in english: "`The value "LWinS" could not be found.`"). I don't know what to do about this... Is that even a proper string representation that I have there? I got it by creating the `HotKey` object manually and printing it to terminal.
Any help would be appreciated.

**Comment by Willy-Kimura** [comment]
No problem.

Looks like the hotkey is not including the `+` delimiter after conversion. There may have been an update that resorts to this behaviour. Try reverting to the previous version `1.8.0` to confirm if it works then let me know.

**Comment by AlphagenCodes** [comment]
@Willy-Kimura can you give an example of the code for saving in settings.  This is what Im doing https://imgur.com/NvixXZM
and to save https://imgur.com/VZhcITc.

**Comment by Willy-Kimura** [comment]
@Mike276alpha basically I meant you can literally save the hotkey in string format to a settings file, e.g.

`File.WriteAllText("C:\my\settings\file.txt", hotkey1.ToString());`
