### ISSUE TITLE
HotkeyListener without modifier

### ISSUE THREAD

**Issue by woth2k3** [Willy-Kimura/HotkeyListener#2]
Hi!

Is it possible to have it without modifier keys?

**Comment by woth2k3** [comment]
And one more question: why am I restricted to two modifiers and one key? I it possible to set only one modifier and one key?

**Comment by Willy-Kimura** [comment]
Hello,

For your first question, yes it's very possible to add a hotkey without modifiers. Simply set a hotkey's modifiers to `Keys.None`. Here's an example:

`[C#]`
`Hotkey hotkey1 = new Hotkey(Keys.None, Keys.T);`

`[VB]`
`Dim hotkey1 As New Hotkey(Keys.None, Keys.T)`

For your second question, there is no restriction to setting modifiers and keys. If you may have noticed in the documentation, there are also some examples with only one modifier and a key.

**Comment by woth2k3** [comment]
I don't know what I was doing, but it's working with only one modifier, that's correct.

However, with "Keys. None" I have 'System.Exception: 'No hotkey registered.''

![Untitled-1](https://user-images.githubusercontent.com/21021805/82840429-3b693b00-9edb-11ea-9aa2-bd2ba0567265.jpg)

Many thanks!

**Comment by woth2k3** [comment]
> For your second question, there is no restriction to setting modifiers and keys. If you may have noticed in the documentation, there are also some examples with only one modifier and a key.

Well, actually, if it's only Shift+Key, there is an error, the hot key is not registered. Control+Key and Alt+Key, Control+Shift+Key and so on are working fine.

**Comment by Willy-Kimura** [comment]
Okay. I'll test a scenario with no modifiers and let you know.

**Comment by Willy-Kimura** [comment]
You can now checkout the latest release.
I've added support for registering hotkeys without modifiers.

Example:

```
var hotkey1 = new Hotkey(Keys.Q);
hkl.Add(hotkey1);
```

Have fun!

**Comment by woth2k3** [comment]
Great! Thanks!
