### ISSUE TITLE
Strange behavior of Google Chrome

### ISSUE THREAD

**Issue by mkopri** [Willy-Kimura/HotkeyListener#20]
Hi!

I just made C# program using HotkeyListener and registred 4 hotkeys:
- Ctrl + Shift + ~
- Ctrl + Shift + 1
- Ctrl + Shift + 2
- Ctrl + Shift + 3

Now when program is running it's accepting hot keys if focused or not. That's what I wanted.
But when Google Chrome is opened and if I press any of those 4 hotkeys, Chrome opens inspect Window.
If I close my program and try same hot keys nothing happens in Chrome.

I tried also other hotkeys, but behavior in chrome stay the same.

What could be wrong?

![image](https://user-images.githubusercontent.com/52380397/136705462-f6827c93-4eb2-40a1-a2ea-163e9aac2913.png)

public partial class Form1 : Form
    {
        static List<S7.Net.Types.DataItem> list = new List<S7.Net.Types.DataItem>();
        static Plc plc = new Plc(CpuType.S71200, "192.168.0.90", 0, 1);
        static HotkeyListener hkl = new HotkeyListener();
        static Hotkey hotkey1 = new Hotkey(Keys.Control | Keys.Shift, Keys.Oemtilde);
        static Hotkey hotkey2 = new Hotkey(Keys.Control | Keys.Shift, Keys.D1);
        static Hotkey hotkey3 = new Hotkey(Keys.Control | Keys.Shift, Keys.D2);
        static Hotkey hotkey4 = new Hotkey(Keys.Control | Keys.Shift, Keys.D3);

         private void Form1_Load(object sender, EventArgs e)
        {
            hkl.Add(new[] { hotkey1, hotkey2, hotkey3, hotkey4 });
            hkl.HotkeyPressed += Hkl_HotkeyPressed;
        }

        private void Hkl_HotkeyPressed(object sender, HotkeyEventArgs e)
        {
            if (e.Hotkey == hotkey1)
                Console.WriteLine("HK1");

            if (e.Hotkey == hotkey2)
                Console.WriteLine("HK2");

            if (e.Hotkey == hotkey3)
                Console.WriteLine("HK3");

            if (e.Hotkey == hotkey4)
                Console.WriteLine("HK4");
            
        }
       private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            hkl.RemoveAll();
        }
}

**Comment by mynameisfoxy** [comment]
Same here. I think all combinations that starts with Ctrl + Shift will toggle dev tools on chrome.

**Comment by Willy-Kimura** [comment]
This is a very much reported behaviour with Chrome. I likewise tested this before releasing the library and confirmed how Chrome intercepts globally registered hotkeys being used in its application window. 

For now unfortunately, try looking for other available hotkey combinations not yet registered with Chrome and test them severally.
