### ISSUE TITLE
How do I change hotkeys

### ISSUE THREAD

**Issue by Ampdale** [Willy-Kimura/HotkeyListener#25]
I have been trying for literally hours now and cannot get it to work!

`hotkey1` is already set to `F7` on startup. I want the user to change the keybind to something else of their choice. How do I go about do so?

` private void Form1_KeyDown(object sender, KeyEventArgs e)

        {

            var hkl = new HotkeyListener();

            if (recordPOS.Text == "Change")

            {

                recordPOS.Text = e.KeyCode.ToString();

                Keys[] keys = (Keys[])typeof(Keys).GetEnumValues();
                Keys pickedKey = keys.FirstOrDefault(k => k.ToString() == recordPOS.Text);

                hkl.Update(ref hotkey1, new Hotkey(pickedKey));
            }
        }`

**Comment by Willy-Kimura** [comment]
Have you tried using the [HotkeySelector](https://github.com/Willy-Kimura/HotkeyListener#the-hotkeyselector-class) input key selection control as defined in the docs?

**Comment by Ampdale** [comment]
This is what I have as my code now. I set textbox1 to "read- only" and when I start the program click on the textbox and press a key that key shows up in the textbox but the hotkey won't set to that key!

`        private void Form1_Load(object sender, EventArgs e)
        {

            var hkl = new HotkeyListener();

            var hks = new HotkeySelector();

            // Define a new hotkey using the Hotkey class. 
            // Parameters are: [modifiers], [keys].
            Hotkey hotkey1 = new Hotkey(Keys.F7);
            Hotkey hotkey2 = new Hotkey(Keys.F8);
            Hotkey hotkey3 = new Hotkey(Keys.F9);

            hkl.Add(hotkey1);
            hkl.Add(hotkey2);
            hkl.Add(hotkey3);
            hkl.HotkeyPressed += Hkl_HotkeyPressed;

            hks.Set(textBox1, hotkey1);
            hks.Enable(textBox1, hotkey1);

        }`

**Comment by roast247** [comment]
can I please get some help?

**Comment by Willy-Kimura** [comment]
Refer to the demo app, [TextClipper](https://github.com/Willy-Kimura/HotkeyListener/tree/master/HotkeyListener.Demos/TextClipper).
