### ISSUE TITLE
PTT Press to Talk - Need to take action while a key is pressed

### ISSUE THREAD

**Issue by e4rthdog** [Willy-Kimura/HotkeyListener#3]
I need to implement a PTT Press To Talk , function in my app..

That is i need to do something while the key is pressed. Is there any way to do that with this library?

Thank you!

**Comment by Willy-Kimura** [comment]
Great question and use-case.

Yes, that is very possible considering HotkeyListener supports the global `KeyPressed` event of any registered keys. You can allow a PTT function to be invoked whenever the end-user presses and holds any registered Hotkey that can be run until they release the Hotkey.

Here's an example:

```
private void HotkeyListener_HotkeyPressed(object sender, HotkeyEventArgs e)
{
    if (e.Hotkey == pttHotkey)
    {
        // Run PTT function until hotkey is released.
        Talk();
    }
}
```
