### ISSUE TITLE
Hotkey class does not handle equality operator with null value

### ISSUE THREAD

**Issue by Ashlanfox** [Willy-Kimura/HotkeyListener#5]
Awesome project you brought here ! 

I found out that your **operator ==** in the _Hotkey_ class does not handle null value (and therefor throws NullException).

**Comment by Willy-Kimura** [comment]
Great. Will have to cater for null-checks probably have this in next release.

**Comment by Willy-Kimura** [comment]
You can now checkout the latest release.
