### ISSUE TITLE
Exception raised in UIAutomationClientsideProviders.dll (see GetTextFromAutomationElement)

### ISSUE THREAD

**Issue by Ashlanfox** [Willy-Kimura/HotkeyListener#6]
Hi again,

Thanks for the release of the 1.3 which I have followed closely.

I'm trying to register a simple {p} hotkey (no modifier) but when I press the key it raises an exception (actually two but they are similar) which I have listed below.

**System.ArgumentException**
![image](https://user-images.githubusercontent.com/20969704/83752928-a815cf80-a669-11ea-9d02-ad065e405412.png)

`A first chance exception of type 'System.ArgumentException' occurred in UIAutomationClientsideProviders.dll

Additional information: Value does not fall within the expected range.`

**System.Windows.Automation.ElementNotAvailableException**
![image](https://user-images.githubusercontent.com/20969704/83752866-87e61080-a669-11ea-9686-b564413511d2.png)

`An exception of type 'System.Windows.Automation.ElementNotAvailableException' occurred in UIAutomationClient.dll and wasn't handled before a managed/native boundary

Additional information: The target element corresponds to UI that is no longer available (for example, the parent window has closed).`

**Comment by Willy-Kimura** [comment]
Most welcome.

Are you running the `HotkeyListener.Demo` project?

**Comment by Ashlanfox** [comment]
> Most welcome.
> 
> Are you running the `HotkeyListener.Demo` project?

No it's not from the demo project. I will try tomorrow with my setup on the demo.

**Comment by Willy-Kimura** [comment]
Okay. 

Kindly download the current `HotkeyListener.Demo` project for testing and provide your feedback once done.
