### ISSUE TITLE
Prevent RegisterHotKey from stopping the default key action?

### ISSUE THREAD

**Issue by Ashlanfox** [Willy-Kimura/HotkeyListener#7]
Hi again,

Is there a functionality to prevent RegisterHotKey from stopping the default action ? The problem is, this is stopping the F2 key from working for other applications, such as Excel.

Couldn't you add a `e.Cancel` field in the `HotkeyEventArgs` for exemple ? If set to `false`, a ` SendKeys.Send("{F2}");` would be sent to the focused window ?

**Comment by Willy-Kimura** [comment]
In that case, you can use HotkeyListener's `Suspend([hotkey])` method. This will allow you to suspend any specific hotkey and later on resume using it by calling the method `Resume([hotkey])`.

**Comment by Ashlanfox** [comment]
> In that case, you can use HotkeyListener's `Suspend([hotkey])` method. This will allow you to suspend any specific hotkey and later on resume using it by calling the method `Resume([hotkey])`.

I have thought of using this logic (much better than an aggressive `SendKeys`) but `Resume() `and `Suspend()` only perform on all Hotkeys (and not specific). I could create a listener for each `Hotkey `but this seems a bit overkill.

**Comment by Willy-Kimura** [comment]
I'll definitely consider adding suspension of specific hotkeys.
For now however, try removing then re-adding a hotkey when needed.

You can also temporarily update a hotkey to another key then re-update to the original key after an action has taken place.

**Comment by Ashlanfox** [comment]
> I'll definitely consider adding suspension of specific hotkeys.
> For now however, try removing then re-adding a hotkey when needed.
> 
> You can also temporarily update a hotkey to another key then re-update to the original key after an action has taken place.

Lovely !

By the way it seems like when hotkeys are suspended and a `WndProc(ref Message m)` is called just afterwards, if the key is an old one then an exception occurs because it tries to access an element in the dictionary that does not exist anymore : 'System.Collections.Generic.KeyNotFoundException'  (see `Hotkey = HotkeyListener.Convert(this.Hotkeys[m.WParam.ToInt32()])).`

**Comment by Willy-Kimura** [comment]
Interesting... Will need take a look at this.

**Comment by Ashlanfox** [comment]
> Interesting... Will need take a look at this.

False alarm, the mistake was on my side...

As the User32 functions (`RegisterHotKey` and `UnregisterHotKey`) are called using the `this` as the handle, I had to `Invoke` on the UI thread everytime I call one of your method that relies on those windows API functions. I forgot to do that for the `suspend()` and `resume()` calls. (which resulted in a silent ignore).

You should consider catching `bool` return value from `HotkeyCore.UnregisterKey` and `HotkeyCore.RegisterKey` for such cases. Maybe, if I'm actually doing it correctly, point the use of `Invoke `if calls are performed on background threads (maybe as a note in the README?).

Sorry again for the false alarm...
I truely love this project and the work you've done here, you're gold !

**Comment by Willy-Kimura** [comment]
Checkout the latest release `v1.4.0`.
