### ISSUE TITLE
Issues with single key hotkey

### ISSUE THREAD

**Issue by iformas** [Willy-Kimura/HotkeyListener#8]
https://github.com/Willy-Kimura/HotkeyListener/blob/90165a660b6d27b8863d6c111bbedd691fc1badb/HotkeyListener/HotkeySelector.cs#L285

_needNonShiftModifier null (Exception) when adding a hotkey with a single key ej:

hotkeyListenner.Add(new Hotkey(Keys.VolumeDown));

**Comment by Willy-Kimura** [comment]
Fixed the issue.
Will be releasing the next version `1.5.0` today or next week.

**Comment by Willy-Kimura** [comment]
Just released the new version [1.5.0](https://www.nuget.org/packages/HotkeyListener/1.5.0).
You may now test registering single hotkeys.

**Comment by iformas** [comment]
Thanks!, now works fine
